spring:
  application:
    name: service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs.path: /auction-system/api/docs/v3/api-docs
  swagger-ui.path: /auction-system/api/docs/
  api-docs:
    groups:
      enabled: true
